---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespace
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster/pod/overlay/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
